//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class User
    {
        public int ID { get; set; }
        public int Row { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        [Index(IsUnique = true)]
        public string Username { get; set; }
        public string Mail { get; set; }
        public string Password { get; set; }
        public string Modify { get; set; }
        public string RegisterDate { get; set; }
        public string Birth { get; set; }
    }
}
